### ISSUE TITLE
Incompatible with ProgressLogging 0.1.1

### ISSUE THREAD

**Issue by devmotion** [tkf/ConsoleProgressMonitor.jl#9]
I noticed that ConsoleProgressMonitor is not compatible with ProgressLogging 0.1.1.

**Comment by tkf** [comment]
Thanks for the bug report. But I actually suggest switching to https://github.com/c42f/TerminalLoggers.jl

ConsoleProgressMonitor.jl was just meant to be kind of a quick solution until something better is created. I should mention this in README.md.

**Comment by devmotion** [comment]
Ah, I see, good to know. Maybe then also the README of ProgressLogging should be updated?

**Comment by tkf** [comment]
Yes, I think that's a good idea.
